spring:
  application:
    name: web-client
  thymeleaf:
    cache: false
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://peer1:9998/eureka,http://peer2:9999/eureka
      