spring:
  application:
    name: eureka-server
--- 
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:9999/eureka
server:
  port: 9998 
--- 
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:9998/eureka
server:
  port: 9999